/// Flutter icons Icon_Panther
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon_Panther
///      fonts:
///       - asset: fonts/Icon_Panther.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icon_Panther {
  Icon_Panther._();

  static const _kFontFam = 'Icon_Panther';
  static const String? _kFontPkg = null;

  static const IconData helmet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
