const lineMarkerData = [
  {'racing_time': '1.05', 'value': 10, 'group': 'rpm'},
  {'racing_time': '2.05', 'value': 11, 'group': 'rpm'},
  {'racing_time': '3.05', 'value': 13, 'group': 'rpm'},
  {'racing_time': '4.05', 'value': 11, 'group': 'rpm'},
  {'racing_time': '5.05', 'value': 12, 'group': 'rpm'},
  {'racing_time': '6.05', 'value': 12, 'group': 'rpm'},
  {'racing_time': '7.05', 'value': 9, 'group': 'rpm'},
  {'racing_time': '1.05', 'value': 1, 'group': 'oil_pressure'},
  {'racing_time': '2.05', 'value': -2, 'group': 'oil_pressure'},
  {'racing_time': '3.05', 'value': 2, 'group': 'oil_pressure'},
  {'racing_time': '4.05', 'value': 5, 'group': 'oil_pressure'},
  {'racing_time': '5.05', 'value': 3, 'group': 'oil_pressure'},
  {'racing_time': '6.05', 'value': 2, 'group': 'oil_pressure'},
  {'racing_time': '7.05', 'value': 0, 'group': 'oil_pressure'},
];
