const lineMarkerData = [
  {'racing_time': '1', 'value': 10, 'group': 'average_rpm'},
  {'racing_time': '2', 'value': 11, 'group': 'average_rpm'},
  {'racing_time': '3', 'value': 13, 'group': 'average_rpm'},
  {'racing_time': '4', 'value': 11, 'group': 'average_rpm'},
  {'racing_time': '5', 'value': 12, 'group': 'average_rpm'},
  {'racing_time': '6', 'value': 12, 'group': 'average_rpm'},
  {'racing_time': '7', 'value': 9, 'group': 'average_rpm'},
  {'racing_time': '1', 'value': 1, 'group': 'oil_pressure'},
  {'racing_time': '2', 'value': -2, 'group': 'oil_pressure'},
  {'racing_time': '3', 'value': 2, 'group': 'oil_pressure'},
  {'racing_time': '4', 'value': 5, 'group': 'oil_pressure'},
  {'racing_time': '5', 'value': 3, 'group': 'oil_pressure'},
  {'racing_time': '6', 'value': 2, 'group': 'oil_pressure'},
  {'racing_time': '7', 'value': 0, 'group': 'oil_pressure'},
];
